[pytest]
pythonpath = monai_ui monai_utils .

# Automatically include coverage options
addopts = 
    --cov=monai_ui 
    --cov=monai_utils 
    --cov-report=term-missing 
    --disable-warnings 
    -q
    

# Ignore data folders and large medical datasets
norecursedirs = 
    data
    data/spleen
    .git
    .venv
    venv

# Make test output cleaner
console_output_style = progress

# Allow PyQt6 tests to run without display server
qt_api = pyqt6

hypothesis_profile = default
